name: Update Daily Quote Page

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-quote:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install requests

    - name: Run Quote Generator Script
      run: python generate_page.py

    - name: Commit and Push if Changed
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name "CodeWithVedang"
        git config --global user.email "shelatkarvedang2@gmail.com"
        git add index.html
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🤖 Update quote"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git push origin main
        fi
    