name: Update Daily Quote Page

on:
  schedule:
    - cron: '0 */12 * * *'  # Every 12 hours
  workflow_dispatch:

jobs:
  update-quote:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository using PAT
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}  # 👈 forces PAT-based checkout

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install requests

    - name: Run Quote Generator Script
      run: python generate_page.py

    - name: Commit and Push Changes
      run: |
        git config user.name "CodeWithVedang"
        git config user.email "shelatkarvedang2@gmail.com"
        git add index.html
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🤖 Update quote"
          git push https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/CodeWithVedang/InspireDailyBot.git HEAD:main
        fi
